// Code generated by go2go; DO NOT EDIT.


//line in.go2:2
package in

//line in.go2:2
import (
//line in.go2:2
 "fmt"
//line in.go2:2
 "testing"
//line in.go2:2
)

//line in.go2:2
type Importable୦ int

//line in.go2:2
var _ = fmt.Errorf
//line in.go2:2
var _ = testing.AllocsPerRun
