// Code generated by go2go; DO NOT EDIT.


//line map.go2:1
package in

//line map.go2:1
import (
//line map.go2:1
 "fmt"
//line map.go2:1
 "testing"
//line map.go2:1
)

//line map.go2:1
var _ = fmt.Errorf
//line map.go2:1
var _ = testing.AllocsPerRun
